// Alloy service agreement — real contract text, populated from proposal fields.
// f = { clientName, clientEntity, clientAddress, effective, track, monthly, setup, termMonths, guarantee, spoc, miles }
export function buildAgreement(f) {
  const S = (n, title, body, subs) => ({ n: String(n), title, body: body || "", subs: subs || [] });
  const sub = (n, title, body) => ({ n, title, body });
  const preamble = `This ALLOY GROWTH PARTNERS & ${f.clientName.toUpperCase()} SERVICE AGREEMENT ("Agreement"), effective as of ${f.effective} ("Effective Date"), is by and between Alloy Growth Partners, LLC ("Alloy"), a limited liability company with a principal place of business at 4908 Manchaca Rd, Austin, TX 78745, and ${f.clientName} ("Client"), a ${f.clientEntity} with a principal place of business at ${f.clientAddress}.

IN CONSIDERATION OF the mutual benefits and obligations set forth in this Agreement, the receipt and sufficiency of which consideration is hereby acknowledged, Alloy and the Client (individually the "Party" and together the "Parties" to this Agreement) agree as follows:`;
  const guarantee = f.guarantee ? [
    sub("8.8", "Growth Guarantee.", `If Client follows the program (defined below) and Client's Growth Return for the Term is less than the program fees Client paid to Alloy during the Term, Alloy will refund the difference by check or ACH. "Growth Return" means the total recurring revenue Client added during the Term, measured at the end of the Term, from new doors (management fee plus ancillary income per door) and new income (new or increased fees, ancillary services and other recurring revenue), as recorded in the Alloy portal and verified by Alloy. Program fees exclude ad spend and other Client expenses, and the refund will not exceed the program fees paid.`),
    sub("8.9", "Following the Program.", `Following the program means that Client: (a) follows each agreed upon annual growth plan and quarterly playbook for three years; (b) participates in the Thrive State workshop and implements the actions agreed there; (c) logs all leads in the Alloy portal and addresses the red flags identified in the playbook, such as closing rate; (d) spends at least 20% of program fees on advertising, in addition to program fees; (e) stays current on action items requested and updates the Alloy portal at least quarterly; and (f) stays current on payments and keeps this Agreement in effect. Client must request the refund in writing within 60 days after the 36 months ends, and Alloy will pay any refund within 30 days after receiving the request. If Client does not follow the program, this guarantee does not apply. The refund is Client's sole remedy if Growth Return falls short of program fees.`),
  ] : [];
  const sections = [
    S(1, "Definitions.", "In this Agreement unless the context otherwise requires:", [
      sub("1.1", "BoardSuite™.", `"BoardSuite" means Alloy's integrated service framework for community association management companies, as described at https://alloygp.co/boardsuite-service/ as of the Effective Date of this Agreement. BoardSuite includes all services available through Alloy's framework, consisting of three core engines—BoardReach (visibility and authority services such as AI search optimization, content marketing, Google Ads & PPC management, national & local SEO, social media marketing, and website development), BoardMatch (alignment and conversion services such as conversion rate optimization, email marketing, follow-up content & email sequences, marketing strategy & campaign planning, proposal optimization, sales messaging & UVP development, and vendor partnership marketing), and BoardRetain (retention and development services such as board education programs to reduce turnover, board portal development, leadership development, role-based training design and development for staff, and employee intranet with optional LMS incorporation)—together with all other related services provided by Alloy as listed in Alloy's Services Hub (as described at https://alloygp.co/services-hub/ as of the Effective Date) to achieve Client's goals. All such services are included in BoardSuite and shall be performed by Alloy based on Client's growth priorities, as documented in Alloy's Project Planning System, with updates subject to mutual written agreement during quarterly reviews (collectively, the "Services").`),
      sub("1.2", "Project Planning System.", `"Project Planning System" means Alloy's documentation and task-management environment used for planning, collaboration, tracking, and oversight of the Services. This system may consist of project management software, documentation tools, or other platforms selected by Alloy from time to time. The Project Planning System will be used to track, prioritize, and adjust the Services in alignment with Client's growth objectives, including quarterly performance reviews, key performance indicators (KPIs), and mutually agreed changes. Client shall be granted access to the portions of the Project Planning System reasonably necessary to review priorities and monitor progress.`),
    ]),
    S(2, "Services.", "", [
      sub("2.1", "Scope of Work.", `Alloy will perform the Services for Client under its BoardSuite framework. The Services shall be provided on an ongoing basis during the term of this Agreement, encompassing all included services with flexibility to adjust priorities quarterly based on Client's evolving growth goals, subject to mutual approval by the Parties. In order to maximize results, services may be modified, added or removed; as the nature of growth services evolve.`),
      sub("2.2", "Schedule.", `Alloy will begin Services within three (3) business days of the Effective Date. The Parties shall schedule a kickoff meeting within ten (10) business days of the Effective Date to align on initial priorities, scope, and high-level timelines (the "Kickoff Meeting"). Thereafter, Alloy shall perform the Services in accordance with the deliverables, priorities, and timelines mutually agreed upon by the designated points of contact during the quarterly planning meetings (the "Planning Meetings"), which shall occur no less frequently than once every calendar quarter.`),
      sub("2.3", "Out of Scope Work.", `During the term of this Agreement, Client may wish to assign additional projects beyond these Services hereunder ("Out-of-Scope Work"). Alloy agrees to accept such Out-of-Scope Work only upon a separate written agreement with Client regarding additional compensation to be paid to Alloy and other relevant terms and conditions. Nothing in this Agreement will be deemed to require Alloy to undertake any act or perform any services which in its good faith judgment would be misleading, false, libelous, unlawful, in breach of a contract, or otherwise prejudicial to Client's or Alloy's interests.`),
    ]),
    S(3, "Exclusivity.", "", [
      sub("3.1", "Exclusivity Obligation.", `Client acknowledges that Alloy works with multiple community association management and service firms nationwide. Alloy shall have no exclusivity obligations to Client unless explicitly provided for in the BoardSuite Investment Track selected by Client in the Proposal (the "Investment Track"). Client has selected the ${f.track} Investment Track.`),
      sub("3.2", "Exclusivity Upgrade.", `If Client elects an Investment Track or service that includes exclusivity, exclusivity shall be defined as follows: Alloy agrees not to enter into a direct marketing services engagement with another HOA management company that operates from an office within ${f.miles} miles of Client's office for services directly competing with services Alloy is providing support for.`),
      sub("3.3", "Term of Exclusivity.", `This exclusivity shall apply during the term of this Agreement and shall not limit Alloy's right to (i) provide services to other community management companies of different size focus, geographic scope, or business model, (ii) provide general marketing resources, products, or training materials that are not customized to Client, or (iii) accept engagements where no material conflict with Client's disclosed market exists. In the event of a breach of this Section, the non-breaching Party may seek remedies as provided in Section 18 (Arbitration).`),
    ]),
    S(4, "Subcontractors.", `Client acknowledges that Alloy may, in the rendition of the Services hereunder, engage third-party developers, suppliers, vendors, and other subcontractors ("Subcontractors") from time to time to provide certain services. Alloy shall supervise such services and endeavor to guard against any loss to Client as the result of the failure of Subcontractors to properly execute their commitments, but Alloy shall not be responsible for their acts or omissions, except where such acts or omissions are due to Alloy's negligence or willful misconduct. If Client enters into arrangements with third parties regarding the provision of materials or services ("Preferred Suppliers") and requests that Alloy utilize such Preferred Suppliers in the discharge of Alloy's obligations hereunder, Client remains solely responsible for such Preferred Suppliers.`),
    S(5, "Client Approval of Materials.", `Alloy shall submit to Client for its approval all elements of any materials to be produced or placed hereunder, including, but not limited to, all copy, layouts, slogans, websites, artworks, graphic materials, and media (together the "Assets"). Submission for prior approval of Assets will not be required to the extent that they are preliminary only.`),
    S(6, "Services to Client's Designees.", `Should Client request Alloy to make purchases for or render services to any parent, subsidiary, or affiliate of Client ("Client Affiliate"), Client and such Client Affiliate shall be jointly and severally liable to Alloy even though Alloy may render invoices to, or in the name of, such Client Affiliate.`),
    S(7, "Relationship of the Parties.", `Alloy's relationship with Client shall be that of an independent contractor and not that of an employee or agent. Neither Alloy, nor any of its employees, shall be entitled to any benefits accorded to Client's employees.`),
    S(8, "Fees, Payments, and Expenses.", "", [
      sub("8.1", "Flat Fee.", `As compensation for the Services rendered pursuant to this Agreement, Client agrees to pay Alloy a flat monthly recurring fee of ${f.monthly} as set forth in the ${f.track} Investment Track, together with a one-time setup fee of ${f.setup}. Promotional Pricing, if any, is valid for 13 months unless otherwise stated elsewhere in this document. The fees for the services provided under this Agreement may be increased annually on the anniversary of the Effective Date in the amount of 6%.`),
      sub("8.2", "Expenses.", `Client shall reimburse Alloy for reasonable out-of-pocket travel expenses, including transportation, lodging, mileage, and meals incurred in rendering Services, as well as all necessary incidental expenses (together the "Expenses"). Incidental expenses include all expenses incurred for Client's account in connection with Alloy's rendition of Services and performance of duties hereunder, including but not limited to the cost of product acquisition, packaging, postage, shipping charges, copyright or trademark charges, and any advertisement buys associated with radio, print, or other media and online sources. Alloy shall obtain Client's prior written authorization before incurring any individual Expense or cost in excess of $99.00. All Expenses not paid directly by Client shall be paid within fifteen (15) days of receipt of Alloy's invoice.`),
      sub("8.3", "Ad Spend Reimbursement.", `Client agrees to reimburse Alloy for any and all advertising charges incurred in connection with Client's ad campaigns on a monthly basis. This includes administrative and credit card processing fees. Alloy will supply Client with ads billing data of Client's ad spend when requested to do so in writing by Client.`),
      sub("8.4", "Taxes.", `Client shall pay, reimburse, and/or hold Alloy harmless for all sales, use, transfer, privilege, tariffs, excise, and all other taxes and all duties, whether international, national, state, or local, however designated, which are levied or imposed by reason of the performance of the Services hereunder, except income taxes.`),
      sub("8.5", "Other Fees.", `Unless otherwise provided in this Agreement, all other services, including Out-of-Scope Work, rendered by Alloy shall be subject to additional compensation under a separate written agreement between Alloy and Client.`),
      sub("8.7", "Payment of Invoices.", `Client agrees to pay all invoices via auto-drafted ACH bank transfer or credit card payment on the first (1st) day of each month and to provide payment details for the same within five (5) days of the Effective Date. Payments not made within such time period shall be subject to late charges equal to one percent (1%) of the overdue amount, per day late. Alloy may suspend all Services for non-payment with seven (7) days advance written notice to Client and may not resume rendering Services until the amounts outstanding are paid in full.`),
      ...guarantee,
    ]),
    S(9, "Trademarks.", `Alloy may create or develop trademarks for Client, in the form of taglines, slogans, logos, designs, or product and brand names (together the "Marks"). Client shall ultimately be responsible for confirming availability and registering such Marks, even though Alloy may assist in coordinating the effort associated with clearing and registering the Marks.`),
    S(10, "Representations and Warranties.", `Alloy represents and warrants to Client that (i) Alloy has full power and authority to enter into this Agreement including all rights necessary to make the foregoing assignments to Client; that in performing under the Agreement; (ii) Alloy will not violate the terms of any agreement with any third party; and (iii) the Services and any work product thereof are the original work of Alloy, do not and will not infringe upon, violate or misappropriate any patent, copyright, trade secret, trademark, contract, or any other publicity right, privacy right, or proprietary right of any third party. Alloy shall defend, indemnify and hold Client and its successors, assigns and licensees harmless from any and all claims, actions and proceedings, and the resulting losses, damages, costs and expenses (including reasonable attorneys' fees) arising from any claim, action or proceeding based upon or in any way related to Alloy's, or its employees, breach or alleged breach of any representation, warranty or covenant in this Agreement, and/or from the acts or omissions of Alloy or its employees.`),
    S(11, "Term and Termination.", "", [
      sub("11.1", "Term.", `This Agreement will commence on the Effective Date and shall continue in full force and effect for ${f.termMonths}.`),
      sub("11.2", "Automatic Renewal.", `This Agreement will automatically renew for an additional twelve (12) months, continually, until non-renewal is requested, in writing, at least sixty (60) days prior to the renewal date.`),
      sub("11.3", "Termination.", `Either Party may terminate this Agreement earlier than the ${f.termMonths} term upon the occurrence of any of the following events: (i) The commission by the other Party of a material breach of this Agreement, which breach is not cured within thirty (30) days of the other Party's receipt of written notice of such breach; or (ii) the other Party has or may be commencing a voluntary or involuntary bankruptcy, receivership or similar proceeding with respect to such other Party.`),
      sub("11.4", "Early Termination.", `Client may terminate this Agreement at any time by paying an early termination fee equal to 75% of the fees due for the duration of their current term, as set forth in Section 8.1, in addition to any outstanding fees due for unpaid invoices, rendered Services, projects, and/or deliverables.`),
    ]),
    S(12, "Protection of Client's Confidential Information.", "", [
      sub("12.1", "Confidential Information.", `Client now owns and will hereafter develop, compile and own certain proprietary techniques, trade secrets, and confidential information which have great value in its business (together the "Client Information"). Client will be disclosing Client Information to Alloy during Alloy's rendering of Services. Client Information includes not only information disclosed by Client, but also information developed or learned by Alloy during Alloy's rendering of Services. Client Information is to be broadly defined and includes all information which has or could have commercial value or other utility in the business in which Client is engaged or contemplates engaging or the unauthorized disclosure of which could be detrimental to the interests of Client, whether or not such information is identified by Client. By way of example and without limitation, Client Information includes any and all information concerning discoveries, developments, designs, improvements, inventions, formulas, processes, techniques, know-how, data, research techniques, customer and supplier lists, marketing, sales or other financial or business information, scripts, and all derivatives, improvements and enhancements to any of the above. Client Information also includes like third-party information which is in Client's possession under an obligation of confidential treatment.`),
      sub("12.2", "Protection of Client Information.", `Alloy agrees that at all times during or subsequent to the performance of Services, Alloy will keep confidential and not divulge, communicate, or use Client Information, except for Alloy's own use during the term of this Agreement to the extent necessary to render Services. Alloy further agrees not to cause the transmission, removal or transport of tangible embodiments of, or electronic files containing, Client Information from Client's principal place of business, without prior written approval of Client.`),
      sub("12.3", "Exceptions.", `Alloy's obligations with respect to any portion of the Client Information as set forth above shall not apply when Alloy can document that (i) it was in the public domain at the time it was communicated to Alloy by Client; (ii) it entered the public domain subsequent to the time it was communicated to Alloy by Client through no fault of Alloy; (iii) it was in Alloy's possession free of any obligation of confidence at the time it was communicated to Alloy by Client; or (iv) it was rightfully communicated to Alloy free of any obligation of confidence subsequent to the time it was communicated to Alloy by Client.`),
      sub("12.4", "Client Property.", `All materials, including without limitation documents, drawings, drafts, notes, designs, computer media, electronic files and lists, including all additions to, deletions from, alterations of, and revisions in the foregoing (together the "Materials"), which are furnished to Alloy by Client or which are developed in the process of rendering Services, or embody or relate to the Services, or the Client Information, are the property of Client, and shall be returned by Alloy to Client promptly at Client's request together with any copies thereof, and in any event promptly upon expiration or termination of this Agreement for any reason. Alloy is granted no rights in or to such Materials or Client Information, except as necessary to fulfill its obligations under this Agreement. Alloy shall not use or disclose the Materials or Client Information to any third party.`),
    ]),
    S(13, "Indemnities.", "", [
      sub("13.1", "Client Indemnity.", `Client shall indemnify, defend, and hold harmless Alloy, its parents, subsidiaries, and affiliated companies, and its and their respective employees, officers, directors, shareholders, and agents (each an "Alloy Indemnitee") from and against any and all Loss incurred by an Alloy Indemnitee based upon or arising out of any third-party claim, allegation, demand, suit, or proceeding (each, a "Claim") made or brought against any Alloy Indemnitee with respect to any advertising, branding, research or other products or services which Alloy prepared or performed for Client hereunder to the extent that such Claim relates, in whole or substantial part, to: (i) the inaccuracy of any information supplied by Client or its agents to Alloy including, without limitation, information concerning Client's products and services, the products or services of Client's competitors or Client's product or service category; (ii) the use of any marketing, branding, research, advertising, packaging, trademark, software, hardware or other materials, or components thereof, furnished by Client or its agents to Alloy to be included in any Assets or media placements; (iii) the use of any materials or data provided or created by Alloy and changed by Client or its agents or used in a manner different from that agreed by the parties; (iv) risks or restrictions known by Client where Client nonetheless elected to proceed; (v) death, personal injury, or product liability (including health and safety) claims or actions arising from the use of Client's products and services; (vi) the unauthorized or improper use of Assets or the Marks by Client, Client's designees, licensees, distributors, franchisees or Client Affiliates; (vii) claims brought by Client's employees for employment discrimination, other employment or labor disputes, breach of contract, personal injury or other civil law matters, or claims brought by those parties with whom Client has a contractual or supplier relationship; (viii) allegations of patent, trademark or trade dress infringement or any other violation of a patent, trademark or trade dress right; (ix) any material breach of the terms of this Agreement by, or any act of omission of, Client or its agents or employees relating to media commitments made by Alloy pursuant to Client's approval as provided for herein; and (x) the negligence, gross negligence, bad faith, or intentional or willful misconduct of Client or its employees, agents or Client Affiliates.`),
      sub("13.2", "Alloy Indemnity.", `Alloy shall indemnify, defend, and hold harmless Client, the Client Affiliates, and their respective employees, members, managers, officers, directors, shareholders, and agents (each a "Client Indemnitee") from and against any and all Loss incurred by a Client Indemnitee based upon or arising out of any Claim made or brought against Client arising out of the production or dissemination of materials produced hereunder that involve (i) libel, slander, defamation, copyright infringement, right of publicity and/or invasion of right of privacy arising out of work created by Alloy and in final form (i.e., ready to be disseminated to the public); or (ii) damage to or destruction of personal property, injury to or death of any person directly attributable to or arising out of Alloy's negligence or willful misconduct in connection with the performance of the Services hereunder.`),
      sub("13.3", "LIMITATION OF LIABILITY.", `EXCLUDING INDEMNIFICATION OBLIGATIONS OR DAMAGES ARISING FROM BREACH OF A PARTY'S CONFIDENTIALITY OBLIGATIONS, NEITHER PARTY SHALL BE LIABLE TO THE OTHER, REGARDLESS OF THE FORM OF ACTION, WHETHER IN CONTRACT, TORT OR OTHERWISE, FOR ANY LOST PROFITS (excluding direct damages for Alloy's anticipated fees), BUSINESS INTERRUPTION, OR FOR ANY INDIRECT, INCIDENTAL, SPECIAL, CONSEQUENTIAL, EXEMPLARY OR PUNITIVE DAMAGES ARISING OUT OF OR RELATING TO THIS AGREEMENT, EVEN IF SUCH PARTY HAS BEEN ADVISED OF THE POSSIBILITY OF SUCH DAMAGES OR LIABILITY, NOR SHALL ALLOY'S AGGREGATE LIABILITY FOR ANY OTHER DAMAGES ARISING OUT OF THIS AGREEMENT EXCEED THE REVENUE PAID BY CLIENT TO ALLOY IN ACCORDANCE WITH THE APPLICABLE SOW.`),
    ]),
    S(14, "Review of Work.", `The Client promises to review the work product, to be reasonably available to Alloy if Alloy has questions regarding Services, and to provide timely feedback and decisions.`),
    S(15, "Rejection of Work.", `Client shall not unreasonably withhold acceptance of any work, projects, and/or the deliverables nor withhold payment(s) under this Agreement. If at any time Client decides, at its sole discretion, that the work, project(s), or any deliverables provided hereunder require modification, Client shall request revisions, in writing, forthwith. Client agrees to provide Alloy every reasonable opportunity to perform requested modifications.`),
    S(16, "Designated Point of Contact.", `Client agrees to designate a single point of contact ("SPOC") to communicate with Alloy regarding all essential business matters. By way of example and without limitation, essential business matters include any work and/or project approvals, purchases, modification requests, goal changes, work or project rejection, Agreement termination, and payment. As of the Effective Date, Client agrees to designate ${f.spoc} as SPOC. Client may designate a new SPOC at any time by providing written notice to Alloy.`),
    S(17, "Ownership and Licenses.", "", [
      sub("17.1", "Work Product.", `All Assets developed or prepared by Alloy or its employees or Subcontractors for Client hereunder that are subject to copyright, trademark, patent, or similar protection shall become the property of Client and deemed "Work Product" provided that (i) the Assets are produced in final form (i.e., ready to be disseminated to the public) by Alloy for Client within six (6) months of being proposed by Alloy and (ii) Client has paid to Alloy all fees and costs associated with creating and, where applicable, producing the Assets. All title and interest to Work Product shall vest in Client as "works made for hire" within the meaning of the United States Copyright Act. To the extent that the title to any such Work Product may not, by operation of law or otherwise, vest in Client as a work made for hire or any such Work Product may not be considered a work made for hire, all right, title and interest therein is hereby irrevocably assigned by Alloy to Client.`),
      sub("17.2", "Third Party Licenses.", `Client understands that Alloy often licenses materials from third parties for inclusion in Work Product. In such circumstances, ownership of such licensed materials remains with the licensor, and Client agrees that it remains bound by the terms of such licenses and that it does not obtain proprietary rights in such third party materials beyond the terms and conditions contained in the pertinent license. Alloy will keep Client informed of any such limitations.`),
      sub("17.3", "Alloy Assets.", `Notwithstanding any other provision of this Agreement, Alloy shall retain all right, title and interest in and to, including any intellectual property rights with respect to, any data, designs, processes, specifications, software, applications, source code, object code, utilities, methodologies, know-how, materials, information and skills (and any derivative works, modifications and enhancements thereto) owned, acquired or developed by Alloy or its licensors, and regardless of whether incorporated in any Work Product, (i) prior to the Effective Date; (ii) independently of, or not in connection with the performance of, the Services; (iii) in the general conduct of its business or to serve general functions that are not specific to Client's unique requirements; or (iv) if generally applicable, non-site specific and unrelated to the "look and feel" of the Assets or other deliverable, in connection with the Services (or partially in connection with the Services) (together the "Alloy Assets"). Subject to fulfillment of Client's payment obligations hereunder, Alloy hereby grants Client a worldwide, perpetual, irrevocable, royalty-free, nonexclusive license, with right to sublicense (but only for the benefit of Client or its permitted successors or assigns), to use Alloy Assets actually incorporated into Work Product pursuant to this Agreement as necessary for or in connection with the use, management and maintenance of such Work Product, provided that Client shall not have the right to publish or distribute any Alloy Assets other than as part of such Work Product or to create derivative works of Alloy Assets.`),
      sub("17.4", "Alloy's Intellectual Property That Is Not Work Product.", `During the term of this Agreement, Alloy might use intellectual property that Alloy owns or has licensed from a third party, but that does not qualify as "work product." This is called "background IP." Possible examples of background IP are pre-existing code, copy, scripts, type fonts, properly-licensed stock photos, and web application tools, including apps. Alloy is not giving the Client this background IP. However, under this Agreement, Alloy is granting the Client a right to use the background IP to develop, market, sell, and support the Client's products and services. The Client may use this background IP worldwide at no additional cost, but it cannot transfer its rights to the background IP. The Client cannot sell or license the background IP separately from its products or services. Alloy reserves the right to revoke this grant for any or all background IP upon termination of this Agreement.`),
      sub("17.5", "Alloy Portfolio.", `Client hereby grants Alloy the right to use the name and service marks of Client in its marketing materials, case studies, or other oral, electronic, or written promotions, which shall include naming Client as a client of Alloy and a brief scope of services provided.`),
    ]),
    S(18, "Arbitration.", `As the exclusive means of initiating adversarial proceedings to resolve any dispute arising under this Agreement, a Party may demand that the dispute be resolved by arbitration administered by the American Arbitration Association in accordance with its commercial arbitration rules.`),
    S(19, "Modification of Agreement.", `Any amendment or modification of this Agreement or additional obligation assumed by either party in connection with this Agreement will only be binding if evidenced in writing signed by each party or an authorized representative of each party.`),
    S(20, "Governing Law and Attorney's Fees.", `The laws of the state of Texas govern the rights and obligations of the Client and Alloy under this Agreement, without regard to conflict of law principles of that state. In any action or suit to enforce any right or remedy under this Agreement or to interpret any provision of this Agreement, the prevailing Party shall be entitled to recover its reasonable attorney's fees, costs and other expenses.`),
    S(21, "Severability.", `If any provision of this Agreement shall be found invalid or unenforceable, the remainder of this Agreement shall be interpreted so as best to reasonably effect the intent of the Parties.`),
    S(22, "Entire Agreement.", `This Agreement, including the Exhibits, constitutes the entire understanding and agreement of the Parties with respect to its subject matter and supersedes all prior and contemporaneous agreements or understandings, inducements or conditions, express or implied, written or oral, between the Parties.`),
    S(23, "Amendment and Waivers.", `Any term or provision of this Agreement may be amended, and the observance of any term of this Agreement may be waived, only by a writing signed by the Party to be bound. The waiver by a Party of any breach or default in performance shall not be deemed to constitute a waiver of any other or succeeding breach or default. The failure of any Party to enforce any of the provisions hereof shall not be construed to be a waiver of the right of such party thereafter to enforce such provisions.`),
    S(24, "Survival.", `Provisions of this Agreement, the performance of which by either or both Parties, or by their sense and context, are intended to survive, will survive the completion, expiration, termination or cancellation of this Agreement.`),
    S(25, "Notices.", `Any notice, demand, or request with respect to this Agreement shall be in writing and shall be effective only if it is delivered by personal service, by air courier with receipt of delivery, or mailed, certified mail, return receipt requested, postage prepaid, to the address set forth above. Such communications shall be effective when they are received by the addressee; but if sent by certified mail in the manner set forth above, they shall be effective five (5) days after being deposited in the mail. Either Party may change its address for such communications by giving notice to the other Party in conformity with this section.`),
  ];
  return { preamble, sections, closing: "IN WITNESS WHEREOF, Alloy and Client have executed this Agreement on the day and date as first appears." };
}
